fixed login button not showing when user not signed in
hyper-scale/race pull request #117
Opened 2021-12-22 12:20 UTC by Aswanth-c

2021-12-22 16:32 UTC, mikefortney requested changes

2021-12-22 16:32 UTC, mikefortney commented on components/Vote/Vote.js
> +        <button className="rounded-r-lg text-white bg-indigo-500 hover:bg-indigo-600 focus:ring-indigo-500 p-2 cursor-not-allowed">
you don't actually need this second instance of the button. you could just add the 'disabled' attribute to the main button if the user is not logged in. much simpler.

2021-12-22 16:32 UTC, mikefortney commented on components/ApplicationDetails/ApplicationDetails.js
> +            {<Vote voteCount={voteCount} onVote={onVote} applicationId={data._id} userSession={session} />}
i would not pass the session, but a boolean if the user is logged in or not

2021-12-23 13:03 UTC, tomknig requested changes
Some ideas for more idiomatic react code:

2021-12-23 13:03 UTC, tomknig commented on components/ApplicationDetails/ApplicationDetails.js
> +            {!session && <Vote voteCount={voteCount} onVote={onVote} applicationId={data._id} isUserlogged={false} />}
```suggestion
            <Vote voteCount={voteCount} onVote={onVote} applicationId={data._id} isUserAuthenticated={session?.authenticated} />
```

I'd like to suggest slightly rephrasing this prop to something like `isUserAuthenticated` and use a boolean value from `session` instead of having the component twice.

2021-12-23 13:03 UTC, tomknig commented on components/ApplicationDetails/ApplicationDetails.js
> +              {!session && <Vote voteCount={voteCount} onVote={onVote} applicationId={data._id} isUserlogged={false} />}
Same here

2021-12-23 13:03 UTC, tomknig commented on components/Vote/Vote.js
> +export default function Vote({ applicationId, voteCount, onVote, isUserlogged }) {
```suggestion
export default function Vote({ applicationId, voteCount, onVote, isUserAuthenticated }) {
```

2021-12-23 13:03 UTC, tomknig commented on components/Vote/Vote.js
> +        disabled={!isUserlogged}
```suggestion
        disabled={!isUserAuthenticated}
```

2021-12-23 13:03 UTC, tomknig commented on components/Vote/Vote.js
> +          (isUserlogged ? "cursor-pointer" : "cursor-not-allowed")
Using `cx` here is maybe a bit clearer:
```suggestion
          cx(
            "rounded-r-lg text-white bg-indigo-500 hover:bg-indigo-600 focus:ring-indigo-500 p-2 cursor-pointer",
            {
              "cursor-not-allowed": !isUserAuthenticated,
            },
          )
```

2021-12-23 13:57 UTC, tomknig approved these changes

2021-12-23 13:57 UTC, merged