added how to get discord guild id on readme
hyper-scale/race pull request #136
Opened 2021-12-28 16:54 UTC by Aswanth-c

2021-12-28 17:12 UTC, kurdybacha requested changes
Thanks for the improvement! Just one comment.

2021-12-28 17:12 UTC, kurdybacha commented on README.md
> +    To get Discord_guild_id Right Click on any  Server you are member of  and copy ID Paste that ID in your local.env
Nit: .env.docker.example is the file used by docker-compose and that one should be updated. local.env is deprecated.

2021-12-28 18:51 UTC, tomknig commented on README.md
> +    To get Discord_guild_id Right Click on any  Server you are member of  and copy ID Paste that ID in your local.env
True. But shouldn’t we change to using .env.docker instead? I know it requires people to cp .env.docker.example, but I think this is common practice and otherwise you constantly have untracked changes in .env.docker.example, which looks a bit dirty to me 🤓

2021-12-28 19:51 UTC, kurdybacha commented on README.md
> +    To get Discord_guild_id Right Click on any  Server you are member of  and copy ID Paste that ID in your local.env
Agreed. We should to that. I remember you mentioned that before. Feel free to create a separate PR for that.

2021-12-29 01:13 UTC, Aswanth-c commented on README.md
> +    To get Discord_guild_id Right Click on any  Server you are member of  and copy ID Paste that ID in your local.env
ok done

2021-12-29 09:27 UTC, merged