Application form
hyper-scale/race pull request #53
Opened 2021-12-14 06:24 UTC by kareemarab

2021-12-14 06:28 UTC, kareemarab commented
This PR still needs work.
Completed: most of basic form design per figma desgn.
Remaining: 
- layout-ing
- drag & drop (browse only might suffice, check w/ core-design)
- link adding
- wiring up to upload api + data mapping

2021-12-15 19:41 UTC, tomknig reviewed
Thank you for working on the application form. I see that you acknowledge the following tasks remain open:
- file upload component // drag & drop functionality for file uploader
- "add link" component
- wiring up to upload api + data mapping

However, I think this implementation deviates quite much from the design. I am not sure how close we want to get to it, but I see many differences, e.g. in terms of:
- background
- color of the pane
- border radiuses
- shadows
- font families, sizes, and weights
- input field appearance
- spacings

Design:
![image](https://user-images.githubusercontent.com/3586316/146253694-1614e97f-36d0-45d4-8b93-9e4d806ee8d4.png)

Implementation:
![image](https://user-images.githubusercontent.com/3586316/146253789-de31af78-9214-430d-bd8b-2b10120af0ca.png)

@kurdybacha and @KevalinKetcham, I'd be curious to hear your oppinions.

2021-12-15 19:47 UTC, kareemarab commented
> Thank you for working on the application form. I see that you acknowledge the following tasks remain open:
> 
> * file upload component // drag & drop functionality for file uploader
> * "add link" component
> * wiring up to upload api + data mapping
> 
> However, I think this implementation deviates quite much from the design. I am not sure how close we want to get to it, but I see many differences, e.g. in terms of:
> 
> * background
> * color of the pane
> * border radiuses
> * shadows
> * font families, sizes, and weights
> * input field appearance
> * spacings
> 
> Design: ![image](https://user-images.githubusercontent.com/3586316/146253694-1614e97f-36d0-45d4-8b93-9e4d806ee8d4.png)
> 
> Implementation: ![image](https://user-images.githubusercontent.com/3586316/146253789-de31af78-9214-430d-bd8b-2b10120af0ca.png)
> 
> @kurdybacha and @KevalinKetcham, I'd be curious to hear your oppinions.

Hey @tomknig, thanks for pointing those things out! I just want to be clear about which version I used. I used the "Current design" in figma as a reference. 

<img width="159" alt="Screen Shot 2021-12-15 at 2 43 16 PM" src="https://user-images.githubusercontent.com/11888150/146254632-4a2c6b82-644b-45ce-b32b-8bff93140f96.png">

I agree some things are off, but my aim was to get the ball rolling with the other components w/ this pr as a foundation. If I'm incorrect about the figma reference, then I can go back and make all the changes, if I'm not then I think the list above gets smaller, no?

2021-12-15 19:53 UTC, tomknig commented
Interesting. But I agree. The design you are looking at doesn't diverge too far from the implementation, that's fine imo. Are we looking at different figmas maybe? I am in https://www.figma.com/file/CPfZkeob1dtxStjSuUUXDs/HyperscalePaid?node-id=1286%3A6710 on the very right in the yellow area of "Latest Eng Ready"

2021-12-15 20:00 UTC, mikefortney requested changes
this is more aesthetic but the first two inputs (and referral) have a nice border/shadow at the bottom but the textareas and link input do not. can they be added?

2021-12-15 20:00 UTC, mikefortney commented on components/ApplicationForm/ApplicationForm.js
> +                        placeholder="Optional"
This is labeled as optional but is actually required. Please make it optional.

2021-12-15 20:00 UTC, mikefortney commented on components/ApplicationForm/ApplicationForm.js
> +                      Add link
add link button needs action. should this add another input for another link?

2021-12-15 20:00 UTC, mikefortney commented on components/ApplicationForm/ApplicationForm.js
> +                    <textarea
this needs a 280 character limit (also needs to be called out in label)

2021-12-15 20:00 UTC, mikefortney commented on components/ApplicationForm/ApplicationForm.js
> +                      Add link
nm i just noticed your note about this needing to be added

2021-12-15 21:22 UTC, kareemarab commented on components/ApplicationForm/ApplicationForm.js
> +                      Add link
yeah, I'll implement that and keep a part of the PR actually. Just realized it's not that big a task.

2021-12-15 21:22 UTC, kareemarab commented on components/ApplicationForm/ApplicationForm.js
> +                    <textarea
yup, fixing that too. Thanks!

2021-12-16 04:16 UTC, kareemarab commented
> Interesting. But I agree. The design you are looking at doesn't diverge too far from the implementation, that's fine imo. Are we looking at different figmas maybe? I am in https://www.figma.com/file/CPfZkeob1dtxStjSuUUXDs/HyperscalePaid?node-id=1286%3A6710 on the very right in the yellow area of "Latest Eng Ready"

I was looking @ the "current design" under Dec. 13. I'll double check w/ core-design and get back to you on this.

2021-12-16 05:17 UTC, mikefortney approved these changes

2021-12-16 06:46 UTC, tomknig commented
> > Interesting. But I agree. The design you are looking at doesn't diverge too far from the implementation, that's fine imo. Are we looking at different figmas maybe? I am in https://www.figma.com/file/CPfZkeob1dtxStjSuUUXDs/HyperscalePaid?node-id=1286%3A6710 on the very right in the yellow area of "Latest Eng Ready"
> 
> 
> 
> @tomknig I was looking @ the "current design" under Dec. 13. I'll double check w/ core-design and get back to you on this.

Ok. Design has responded. Looks like this PR is not yet implementing the latest design: https://discord.com/channels/916751469678579784/918664975998930954/920918234063061012

How do we want to proceed? Implementing latest design as a follow up or adapt as a part of this PR?

2021-12-16 09:17 UTC, kurdybacha commented
Let's merge it and we can address in the follow up PR.
Nice work!

2021-12-16 09:17 UTC, merged