Use tailwind
hyper-scale/race pull request #78
Opened 2021-12-15 07:08 UTC by quick007

I developed this with out seeing the live preview but it probably is fine

2021-12-16 05:19 UTC, mikefortney requested changes

2021-12-16 05:19 UTC, mikefortney commented on tailwind.config.js
> +        "fold-lines": "calc(80rem+200px)",
this doesn't seem to be working, as the width of the div is screen width, not 80rem + 200px

2021-12-16 06:18 UTC, quick007 commented on tailwind.config.js
> +        "fold-lines": "calc(80rem+200px)",
I was just converting the original CSS, not fixing it (mainly cause I couldn't get live preview working)
![image](https://user-images.githubusercontent.com/69743171/146318603-9807b116-7e68-4e22-a4f7-661073fed9f9.png)

2021-12-16 16:38 UTC, mikefortney commented on tailwind.config.js
> +        "fold-lines": "calc(80rem+200px)",
I see. Well, the width was working before. So please either get the width working or return the width to inline style. Thanks!

2021-12-19 10:18 UTC, kurdybacha commented
@quick007 I will close this PR for now. Feel free to reopen when you have time to address the comments.

2021-12-19 10:18 UTC, closed without merging