Feature/mailservice
hyper-scale/race pull request #99
Opened 2021-12-19 18:28 UTC by Aswanth-c

added mail configuration  and mail sending feature 
use sendApplicationReceivedMail function to send application has been received to a mail it takes 2 parameters  their name and email  
in order to use it 
fill these env variables in your local respective  to your's email 
MAIL_PORT=
MAIL_HOST=
MAIL_USER=
MAIL_PASSWORD=
MAIL_FROM 
mail template is on hbs files

2021-12-19 18:36 UTC, tomknig requested changes
1. There are some inconsistencies here wrt. indentation. CI is passing because the new directory `mail` is not yet included for linting. We should add it in the `package.json`.
2. Is this really the approach we want to take? I think manually sent mails, without proper dkim detup etc., are quite likely to bounce. How about using email SaaS for that?

2021-12-19 18:36 UTC, tomknig commented on mail/template/applicationreceived.handlebars
> +<p>
There are some extra spaces and a missing closing tag here.
```suggestion
<p>your application has been received.</p>
<p></p> /* or remove this tag altogether */
```

2021-12-19 21:06 UTC, kurdybacha commented on mail/template/applicationreceived.handlebars
> +<p>
I don't have much experience with this approach. Does it require some smtp server configuration? If yes then maybe the simplest and most reliable would be to use some SaaS service as @tomknig is suggesting. What do you think @Aswanth-c ?

2021-12-20 04:25 UTC, Aswanth-c commented on mail/template/applicationreceived.handlebars
> +<p>
yes it required smtp connection.  im not sure which way is good. if using a saas is better than this we can go forward with it

2021-12-20 19:55 UTC, tomknig requested changes
I guess this is a good starting point. Thx!
Few observations:
1. Please remove the unused dependencies `nodemailer`, `nodemailer-express-handlebars`.
2. Please add the required dependency `@sendgrid/mail`
3. Please add `mail` to the `lint` and `format` scripts in the `package.json`. I see some inconsistent formatting.

2021-12-21 13:24 UTC, merged